---
- name: Converge
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: "Include daixijun.mysql"
      include_role:
        name: "daixijun.mysql"
      vars:
        mysql_root_password: Uiteewieh=ohJ1yuhu4k
        mysql_repl_password: goh?she5ahpheiYi5ahY
        mysql_innodb_cluster_password: hai0AiV7chaig5pheo=Z
        mysql_group_replication_name: 231e852b-fa3f-4c82-b2eb-4b85eb3d03bd
      when:
        - inventory_hostname in groups['mysql']
    - name: "Include daixijun.mysqlrouter"
      include_role:
        name: "daixijun.mysqlrouter"
      vars:
        mysqlrouter_bootstrap_server_url: "ic:hai0AiV7chaig5pheo=Z@{{ hostvars['mysql-primary']['ansible_default_ipv4']['address'] }}:3306"
      when:
        - inventory_hostname == 'mysql-router'
